SELECT *
WHERE
{
?d1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/CombinationAntibiotics> .
?d1 <http://dbpedia.org/property/routesOfAdministration> ?m .
?d1 <http://dbpedia.org/property/smiles> ?sm1 .
}
